Feature: Refactor Sudoku Solver Project Boilerplate for a Backend Focus to Improve Testability
freeCodeCamp/boilerplate-project-sudoku-solver pull request #8
Opened 2020-10-05 19:24 UTC by SaintPeter

As discussed here:
https://github.com/freeCodeCamp/freeCodeCamp/issues/39692

@nhcarrigan and I refactored this project to have a more backend focus to improve testability by the fCC test infrastructure.

Key Changes:
* Removed all front-end related User Stories 
* Rewrote the front-end to provide minimal features, treating it as a basic API endpoint test
* Added a new requirement to check the validity of an individual value's placement
* Rewrote both the unit tests to cover the algorithm in more depth
  * Added specific tests for checking placement for row/column/region
* Rewrote functional tests to cover the two new endpoints.

NOTE: This change should not be merged until the (as yet uncreated) `/learn` PR has been completed.

2020-10-12 18:10 UTC, Sky020 requested changes, later dismissed
Some clarification about these changes:
- We have decided to remove the block name from the headings, to prevent the case where the project is moved, and then need to update the boilerplate READMEs

Otherwise, looking good, Rex

2020-10-12 18:10 UTC, Sky020 commented on README.md
> +### [Quality Assurance Projects - Sudoku Solver](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/sudoku-solver)
```suggestion
# [Sudoku Solver](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/sudoku-solver)
```

2020-10-13 15:51 UTC, Sky020 commented on views/index.html
> +			Quality Assurance 4: Sudoku Solver
```suggestion
			Sudoku Solver
```

2020-10-13 15:55 UTC, Sky020 commented on controllers/sudoku-solver.js
> +  //if string length is < 81, return "You too short man"
Does this serve any purpose?

2020-10-13 15:58 UTC, naomi-lgbt commented on controllers/sudoku-solver.js
> +  //if string length is < 81, return "You too short man"
The comment? Nope. I think that's left over from our whiteboarding process 😅

2020-10-13 16:04 UTC, ShaunSHamilton commented on controllers/sudoku-solver.js
> +  //if string length is < 81, return "You too short man"
Right. Rex, could you remove it, then.

Thanks, for all of this. You two have done excellent work

2020-10-13 16:39 UTC, SaintPeter commented on views/index.html
> +			Quality Assurance 4: Sudoku Solver
This is resolved in the latest commit.

2020-10-14 19:41 UTC, SaintPeter commented
This should be good to go now.

2020-10-20 16:08 UTC, moT01 approved these changes
LGTM 🎉 

My testing process was to run all three PR's for this project locally, submit the demo project on the website - then move the code from there into the few files on this one and submit that - it went smooth and I think I am good with this.

2020-11-06 18:04 UTC, RandellDawson commented
@Sky020 If you are ok with the changes, I am too, so you can approve and then we can just wait for the `/learn` PR changes to hit production once that PR is merged.

2020-11-07 19:25 UTC, moT01 approved these changes
LGTM 🎉 - The PR to main repo is now on production so we should merge this to prevent confusion. Thanks again for all the work on these @SaintPeter @nhcarrigan 🎉

2020-11-07 19:26 UTC, merged